import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { getCloudinaryPublicConfig } from "@/lib/cloudinary";
import { trpc } from "@/lib/trpc";
import { Link, useLocation } from "wouter";
import { BarChart3, Boxes, ChevronLeft, CircleDollarSign, ClipboardList, ExternalLink, Layers3, Palette, Plus, Settings2, ShoppingBag, Sparkles, Store, WandSparkles } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { toast } from "sonner";

type SettingForm = { brandName: string; wordmark: string; tagline: string; description: string; primaryColor: string; surfaceColor: string; heroTitle: string; heroSubtitle: string; heroImageUrl: string; heroCtaLabel: string; announcementText: string; };
type ProductRow = { id: string; name: string; slug: string; subtitle?: string; description: string; category: "sneakers" | "gym" | "streetwear"; gender: "men" | "women" | "unisex"; priceCents: number; compareAtCents?: number | null; badge?: string | null; material?: string | null; isFeatured: boolean; images: { url: string }[]; variants: { id: string; shopifyVariantId?: string | null; sku: string; colorName: string; colorHex: string; size: string; stockQuantity: number; isAvailable: boolean }[]; };
type CollectionRow = { id: string; title: string; slug: string; description: string; category: "sneakers" | "gym" | "streetwear" | "featured"; imageUrl?: string | null; kicker?: string | null; };
type CampaignRow = { id: string; title: string; slug: string; description: string; type: "drop" | "lookbook" | "offer"; imageUrl?: string | null; kicker?: string | null; ctaLabel: string; };
type OrderStatus = "new" | "confirmed" | "preparing" | "shipped" | "completed" | "cancelled";
type OrderRow = { id: number; orderNumber: string; customerName: string; phone: string; address: string; notes?: string | null; paymentMethod: "cod"; status: OrderStatus; totalCents: number; createdAt: string | Date; items: { productName: string; variantLabel: string; quantity: number; unitPriceCents: number; imageUrl?: string | null }[]; };

const EMPTY_SETTINGS: SettingForm = { brandName: "LUXORA", wordmark: "LX", tagline: "Streetwear / Performance", description: "", primaryColor: "#D9FF2F", surfaceColor: "#101010", heroTitle: "MOVE DIFFERENT.", heroSubtitle: "", heroImageUrl: "", heroCtaLabel: "تسوّق الإصدار", announcementText: "" };
const demoImage = "https://res.cloudinary.com/dbt9psvo/image/upload/luxora-product-streetwear_37edd00f";

function pounds(cents: number) { return new Intl.NumberFormat("ar-EG").format(Math.round(cents / 100)); }

function AdminShell({ children, active, onActive }: { children: React.ReactNode; active: string; onActive: (value: string) => void }) {
  const links = [
    ["overview", "نظرة عامة", BarChart3], ["brand", "هوية المتجر", Palette], ["products", "المنتجات", ShoppingBag], ["collections", "المجموعات", Layers3], ["campaigns", "الحملات", Sparkles], ["orders", "الطلبات", ClipboardList], ["shopify", "Shopify", Store],
  ] as const;
  return <div dir="rtl" className="min-h-screen overflow-x-hidden bg-[#0c0c0c] text-white"><header className="sticky top-0 z-30 border-b border-white/10 bg-[#0c0c0c]/90 backdrop-blur"><div className="container flex h-16 items-center justify-between"><Link href="/" className="flex items-center gap-2 text-sm font-black tracking-[.18em]"><span className="grid h-8 w-8 place-items-center rounded-full border border-[var(--lux-acid)] text-[10px] text-[var(--lux-acid)]">LX</span>LUXORA <span className="text-[9px] font-bold tracking-[.12em] text-white/35">CONTROL ROOM</span></Link><Link href="/" className="flex items-center gap-2 text-xs font-bold text-white/60 hover:text-[var(--lux-acid)]">زيارة المتجر <ExternalLink className="h-3.5 w-3.5" /></Link></div></header><div className="container grid min-w-0 gap-6 py-6 lg:grid-cols-[220px_minmax(0,1fr)]"><aside className="lg:sticky lg:top-24 lg:h-fit"><p className="mb-3 px-2 text-[9px] font-black tracking-[.15em] text-white/35">MANAGE THE SYSTEM</p><nav className="flex min-w-0 gap-2 overflow-x-auto pb-2 lg:flex-col">{links.map(([id, label, Icon]) => <button key={id} onClick={() => onActive(id)} className={`flex shrink-0 items-center gap-3 rounded-sm px-3 py-3 text-right text-xs font-bold transition ${active === id ? "bg-[var(--lux-acid)] text-black" : "text-white/55 hover:bg-white/7 hover:text-white"}`}><Icon className="h-4 w-4" />{label}</button>)}</nav></aside><section className="min-w-0 overflow-hidden">{children}</section></div></div>;
}

function LoginGate() {
  const mode = trpc.auth.mode.useQuery(undefined, { retry: false, refetchOnWindowFocus: false });
  const standalone = mode.data?.standalone === true;
  const [password, setPassword] = useState("");
  const ownerLogin = trpc.auth.ownerLogin.useMutation({
    onSuccess: () => window.location.reload(),
    onError: error => toast.error(error.message),
  });
  const submit = (event: FormEvent) => {
    event.preventDefault();
    if (!password.trim()) return toast.error("أدخل كلمة مرور لوحة التحكم.");
    ownerLogin.mutate({ password });
  };
  return <main dir="rtl" className="grid min-h-screen place-items-center bg-[#0c0c0c] px-5 text-white"><div className="max-w-md border border-white/10 bg-[#151515] p-7 text-center"><span className="mx-auto grid h-12 w-12 place-items-center rounded-full bg-[var(--lux-acid)] text-black"><Settings2 className="h-5 w-5" /></span><p className="mt-6 text-[10px] font-black tracking-[.14em] text-[var(--lux-acid)]">LUXORA / ADMIN</p><h1 className="mt-3 font-display text-4xl font-black">لوحة التحكم.</h1><p className="mt-4 text-sm leading-7 text-white/55">{standalone ? "أدخل كلمة مرور مالك LUXORA للوصول إلى إدارة البراند والكتالوج والحملات." : "سجّل الدخول بحساب مالك المشروع للوصول إلى إدارة البراند والكتالوج والحملات."}</p>{mode.isLoading ? <div className="mt-7 h-12 animate-pulse bg-white/10" /> : standalone ? <form onSubmit={submit} className="mt-7"><label className="sr-only" htmlFor="luxora-admin-password">كلمة المرور</label><input id="luxora-admin-password" value={password} onChange={event => setPassword(event.target.value)} type="password" autoComplete="current-password" className="h-12 w-full border border-white/15 bg-[#101010] px-3 text-center text-sm text-white outline-none focus:border-[var(--lux-acid)]" placeholder="كلمة مرور لوحة التحكم" /><button disabled={ownerLogin.isPending} className="mt-3 h-12 w-full bg-[var(--lux-acid)] text-sm font-black text-black disabled:opacity-60">{ownerLogin.isPending ? "جارٍ التحقق..." : "دخول لوحة التحكم"}</button></form> : <button onClick={() => startLogin()} className="mt-7 h-12 w-full bg-[var(--lux-acid)] text-sm font-black text-black">تسجيل الدخول</button>}<Link href="/" className="mt-4 block text-xs font-bold text-white/45">العودة للمتجر</Link></div></main>;
}

function Overview({ products, collections, campaigns, bootstrap, busy }: { products: ProductRow[]; collections: CollectionRow[]; campaigns: CampaignRow[]; bootstrap: () => void; busy: boolean }) {
  const inventory = products.reduce((sum, product) => sum + product.variants.reduce((count, variant) => count + variant.stockQuantity, 0), 0);
  return <><PageTitle kicker="CONTROL ROOM / 01" title="كل شيء تحت السيطرة." text="هذه لوحة إدارة مستقلة؛ تعدّل منها الهوية والمحتوى والكتالوج بدون لمس أي موقع آخر." /><div className="mt-8 grid gap-3 sm:grid-cols-3"><Metric label="منتجات في الواجهة" value={String(products.length)} icon={ShoppingBag} /><Metric label="قطع بالمخزون" value={String(inventory)} icon={Boxes} /><Metric label="حملات تحريرية" value={String(campaigns.length)} icon={Sparkles} /></div><div className="mt-6 grid gap-4 lg:grid-cols-[1.15fr_.85fr]"><div className="border border-white/10 bg-[#151515] p-5 sm:p-6"><p className="text-[10px] font-black tracking-[.14em] text-[var(--lux-acid)]">QUICK START</p><h2 className="mt-3 font-display text-3xl font-black">ابدأ من الهوية، ثم الكتالوج.</h2><p className="mt-3 max-w-xl text-sm leading-7 text-white/55">المتجر يعمل حاليًا بقالب تجريبي قابل للاستبدال. يمكنك تعبئة النموذج التجريبي داخل قاعدة البيانات لتبدأ تعديله، أو إدخال منتجاتك وحملاتك يدويًا من التبويبات المجاورة.</p><button onClick={bootstrap} disabled={busy} className="mt-6 inline-flex h-11 items-center gap-2 bg-[var(--lux-acid)] px-4 text-xs font-black text-black disabled:opacity-60"><WandSparkles className="h-4 w-4" />{busy ? "يتم التجهيز..." : "تعبئة محتوى البداية"}</button></div><div className="border border-white/10 bg-[#151515] p-5 sm:p-6"><p className="text-[10px] font-black tracking-[.14em] text-white/40">CATALOG STATE</p><div className="mt-5 space-y-4 text-sm"><StateLine label="المجموعات" value={`${collections.length} جاهزة`} /><StateLine label="الصور" value="روابط قابلة للاستبدال" /><StateLine label="الدفع" value="ينتظر Shopify" /></div></div></div></>;
}
function Metric({ label, value, icon: Icon }: { label: string; value: string; icon: typeof ShoppingBag }) { return <div className="border border-white/10 bg-[#151515] p-5"><Icon className="h-4 w-4 text-[var(--lux-acid)]" /><p className="mt-5 font-display text-4xl font-black">{value}</p><p className="mt-1 text-xs font-bold text-white/45">{label}</p></div>; }
function StateLine({ label, value }: { label: string; value: string }) { return <div className="flex items-center justify-between border-b border-white/10 pb-3 last:border-0"><span className="text-white/55">{label}</span><span className="font-bold text-white">{value}</span></div>; }
function PageTitle({ kicker, title, text, action }: { kicker: string; title: string; text: string; action?: React.ReactNode }) { return <div className="flex flex-wrap items-end justify-between gap-5 border-b border-white/10 pb-6"><div><p className="text-[10px] font-black tracking-[.14em] text-[var(--lux-acid)]">{kicker}</p><h1 className="mt-3 font-display text-4xl font-black tracking-[-.05em] sm:text-5xl">{title}</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-white/55">{text}</p></div>{action}</div>; }
function Field({ label, value, onChange, placeholder, type = "text" }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string; type?: string }) { return <label className="block"><span className="mb-2 block text-[10px] font-black tracking-[.08em] text-white/50">{label}</span><input value={value} type={type} onChange={event => onChange(event.target.value)} placeholder={placeholder} className="h-11 w-full rounded-sm border border-white/15 bg-[#101010] px-3 text-sm text-white outline-none transition placeholder:text-white/25 focus:border-[var(--lux-acid)]" /></label>; }
function TextArea({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="block"><span className="mb-2 block text-[10px] font-black tracking-[.08em] text-white/50">{label}</span><textarea value={value} onChange={event => onChange(event.target.value)} rows={4} className="w-full rounded-sm border border-white/15 bg-[#101010] px-3 py-3 text-sm leading-6 text-white outline-none transition focus:border-[var(--lux-acid)]" /></label>; }
function CloudinaryImageUpload({ onUploaded }: { onUploaded: (url: string) => void }) {
  const config = getCloudinaryPublicConfig(import.meta.env);
  const [uploading, setUploading] = useState(false);
  if (!config) return <p className="mt-2 text-[10px] font-bold text-white/35">يمكنك لصق رابط الصورة الآن. سيتاح الرفع من الجهاز فور إعداد تخزين الصور المستقل.</p>;
  const upload = async (file?: File) => {
    if (!file) return;
    if (!file.type.startsWith("image/")) return toast.error("اختر ملف صورة صالحًا.");
    if (file.size > 10 * 1024 * 1024) return toast.error("حجم الصورة يجب أن يكون 10MB أو أقل.");
    setUploading(true);
    try {
      const body = new FormData();
      body.append("file", file);
      body.append("upload_preset", config.uploadPreset);
      body.append("folder", "LUXORA");
      const response = await fetch(`https://api.cloudinary.com/v1_1/${config.cloudName}/image/upload`, { method: "POST", body });
      const result = await response.json() as { secure_url?: string; error?: { message?: string } };
      if (!response.ok || !result.secure_url) throw new Error(result.error?.message || "تعذر رفع الصورة.");
      onUploaded(result.secure_url);
      toast.success("تم رفع الصورة إلى مكتبة LUXORA.");
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "تعذر رفع الصورة.");
    } finally {
      setUploading(false);
    }
  };
  return <label className="mt-3 flex h-11 cursor-pointer items-center justify-center border border-dashed border-white/20 px-3 text-xs font-bold text-white/70 transition hover:border-[var(--lux-acid)] hover:text-[var(--lux-acid)]"><input className="sr-only" type="file" accept="image/png,image/jpeg,image/webp" disabled={uploading} onChange={event => void upload(event.target.files?.[0])} />{uploading ? "جارٍ رفع الصورة..." : "رفع صورة من الجهاز"}</label>;
}

function BrandEditor({ settings, saving, onSave }: { settings: SettingForm; saving: boolean; onSave: (settings: SettingForm) => void }) {
  const [form, setForm] = useState(settings);
  useEffect(() => setForm(settings), [settings]);
  const set = (key: keyof SettingForm) => (value: string) => setForm(previous => ({ ...previous, [key]: value }));
  return <form onSubmit={event => { event.preventDefault(); onSave(form); }}><PageTitle kicker="BRAND SYSTEM / 02" title="غيّر البراند من هنا." text="الاسم، الألوان، نصوص الصفحة الرئيسية وصورة الحملة محفوظة في إعدادات مستقلة، لتسهيل إعادة العلامة التجارية." action={<button className="h-11 bg-[var(--lux-acid)] px-5 text-xs font-black text-black disabled:opacity-60" disabled={saving}>{saving ? "جارٍ الحفظ..." : "حفظ الهوية"}</button>} /><div className="mt-8 grid gap-4 lg:grid-cols-2"><Panel title="الاسم والشخصية"><div className="grid gap-4 sm:grid-cols-2"><Field label="اسم البراند" value={form.brandName} onChange={set("brandName")} /><Field label="رمز الشعار" value={form.wordmark} onChange={set("wordmark")} /><Field label="السطر التعريفي" value={form.tagline} onChange={set("tagline")} /></div><div className="mt-4"><TextArea label="وصف المتجر" value={form.description} onChange={set("description")} /></div></Panel><Panel title="نظام اللون"><div className="grid gap-4 sm:grid-cols-2"><Field label="لون التمييز" type="color" value={form.primaryColor} onChange={set("primaryColor")} /><Field label="لون الخلفية" type="color" value={form.surfaceColor} onChange={set("surfaceColor")} /></div><div className="mt-5 flex h-20 items-center justify-between px-5 text-black" style={{ background: form.primaryColor }}><strong className="font-display text-2xl font-black">{form.brandName || "BRAND"}</strong><span className="text-xs font-bold">Accent preview</span></div></Panel><Panel title="الحملة الرئيسية" className="lg:col-span-2"><div className="grid gap-4 lg:grid-cols-2"><Field label="عنوان Hero" value={form.heroTitle} onChange={set("heroTitle")} /><Field label="زر الـ Hero" value={form.heroCtaLabel} onChange={set("heroCtaLabel")} /><div className="lg:col-span-2"><TextArea label="النص التوضيحي" value={form.heroSubtitle} onChange={set("heroSubtitle")} /></div><div className="lg:col-span-2"><Field label="رابط صورة الـ Hero" value={form.heroImageUrl} onChange={set("heroImageUrl")} placeholder="https://..." /><CloudinaryImageUpload onUploaded={set("heroImageUrl")} /></div><div className="lg:col-span-2"><Field label="الشريط العلوي" value={form.announcementText} onChange={set("announcementText")} /></div></div></Panel></div></form>;
}
function Panel({ title, children, className = "" }: { title: string; children: React.ReactNode; className?: string }) { return <section className={`border border-white/10 bg-[#151515] p-5 sm:p-6 ${className}`}><h2 className="mb-5 text-sm font-black">{title}</h2>{children}</section>; }

function ProductForm({ title, initial, saving, onSubmit }: { title: string; initial?: ProductRow | null; saving: boolean; onSubmit: (input: { name: string; slug: string; category: "sneakers" | "gym" | "streetwear"; price: string; image: string; description: string; gender: "men" | "women" | "unisex"; featured: boolean }) => void }) {
  const [name, setName] = useState(initial?.name ?? ""); const [slug, setSlug] = useState(initial?.slug ?? ""); const [category, setCategory] = useState<"sneakers" | "gym" | "streetwear">(initial?.category ?? "streetwear"); const [price, setPrice] = useState(initial ? String(initial.priceCents / 100) : ""); const [image, setImage] = useState(initial?.images[0]?.url ?? demoImage); const [description, setDescription] = useState(initial?.description ?? ""); const [gender, setGender] = useState<"men" | "women" | "unisex">(initial?.gender ?? "unisex"); const [featured, setFeatured] = useState(initial?.isFeatured ?? false);
  return <Panel title={title} className="mt-6"><form onSubmit={event => { event.preventDefault(); onSubmit({ name, slug, category, price, image, description, gender, featured }); }} className="grid gap-4 md:grid-cols-2"><Field label="اسم المنتج" value={name} onChange={value => { setName(value); if (!initial) setSlug(value.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "")); }} /><Field label="Slug بالإنجليزية" value={slug} onChange={setSlug} /><label><span className="mb-2 block text-[10px] font-black tracking-[.08em] text-white/50">الفئة</span><select value={category} onChange={event => setCategory(event.target.value as typeof category)} className="h-11 w-full border border-white/15 bg-[#101010] px-3 text-sm text-white outline-none"><option value="sneakers">كوتشيات</option><option value="gym">ملابس جيم</option><option value="streetwear">ملابس شبابية</option></select></label><label><span className="mb-2 block text-[10px] font-black tracking-[.08em] text-white/50">الجمهور</span><select value={gender} onChange={event => setGender(event.target.value as typeof gender)} className="h-11 w-full border border-white/15 bg-[#101010] px-3 text-sm text-white outline-none"><option value="unisex">Unisex</option><option value="men">Men</option><option value="women">Women</option></select></label><Field label="السعر بالجنيه" value={price} onChange={setPrice} type="number" /><label className="flex h-11 items-center gap-3 self-end border border-white/15 px-3 text-xs font-bold"><input type="checkbox" checked={featured} onChange={event => setFeatured(event.target.checked)} />إظهار ضمن المختارات</label><div className="md:col-span-2"><Field label="رابط صورة المنتج" value={image} onChange={setImage} /><CloudinaryImageUpload onUploaded={setImage} /></div><div className="md:col-span-2"><TextArea label="وصف المنتج" value={description} onChange={setDescription} /></div><button disabled={saving} className="h-11 bg-[var(--lux-acid)] text-xs font-black text-black disabled:opacity-60">{saving ? "جارٍ الحفظ..." : "حفظ المنتج"}</button></form></Panel>;
}

function InventoryEditor({ product, saving, onSave }: { product: ProductRow; saving: boolean; onSave: (variants: ProductRow["variants"], imageUrls: string[]) => void }) {
  const [variants, setVariants] = useState(product.variants); const [urls, setUrls] = useState(product.images.map(image => image.url).join("\n"));
  const change = (index: number, key: "colorName" | "colorHex" | "size" | "stockQuantity" | "isAvailable", value: string | boolean) => setVariants(items => items.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: key === "stockQuantity" ? Math.max(0, Number(value) || 0) : value } : item));
  const add = () => setVariants(items => [...items, { id: `new-${Date.now()}`, sku: `LX-${product.slug.toUpperCase()}-${items.length + 1}`, colorName: "Black", colorHex: "#151515", size: "M", stockQuantity: 1, isAvailable: true }]);
  return <Panel title={`المقاسات والمخزون / ${product.name}`} className="mt-6"><p className="mb-5 text-xs leading-6 text-white/50">عدّل اللون والمقاس والكمية لكل Variant. المنتج يظهر تلقائيًا غير متاح عند إيقافه أو جعل كميته صفرًا.</p><div className="overflow-x-auto"><div className="min-w-[620px] space-y-2">{variants.map((variant, index) => <div key={variant.id} className="grid grid-cols-[1.2fr_70px_75px_85px_62px_30px] items-center gap-2"><input value={variant.colorName} onChange={event => change(index, "colorName", event.target.value)} className="h-10 border border-white/15 bg-[#101010] px-2 text-xs outline-none" /><input type="color" value={variant.colorHex} onChange={event => change(index, "colorHex", event.target.value)} className="h-10 border border-white/15 bg-[#101010] p-1" /><input value={variant.size} onChange={event => change(index, "size", event.target.value)} className="h-10 border border-white/15 bg-[#101010] px-2 text-xs outline-none" /><input type="number" min="0" value={variant.stockQuantity} onChange={event => change(index, "stockQuantity", event.target.value)} className="h-10 border border-white/15 bg-[#101010] px-2 text-xs outline-none" /><label className="flex items-center justify-center"><input type="checkbox" checked={variant.isAvailable} onChange={event => change(index, "isAvailable", event.target.checked)} /></label><button type="button" onClick={() => setVariants(items => items.filter((_, itemIndex) => itemIndex !== index))} className="text-red-300">×</button></div>)}</div></div><button type="button" onClick={add} className="mt-4 text-xs font-bold text-[var(--lux-acid)]">+ إضافة مقاس أو لون</button><div className="mt-6 border-t border-white/10 pt-5"><TextArea label="روابط صور المنتج (رابط في كل سطر)" value={urls} onChange={setUrls} /><CloudinaryImageUpload onUploaded={url => setUrls(previous => previous ? `${previous}\n${url}` : url)} /></div><button type="button" disabled={saving} onClick={() => onSave(variants, urls.split("\n").map(url => url.trim()).filter(Boolean))} className="mt-5 h-11 bg-[var(--lux-acid)] px-5 text-xs font-black text-black disabled:opacity-60">{saving ? "جارٍ الحفظ..." : "حفظ المخزون والصور"}</button></Panel>;
}

function ProductManager({ products, saving, onCreate, onUpdate, onDelete, onInventory }: { products: ProductRow[]; saving: boolean; onCreate: (input: { name: string; slug: string; category: "sneakers" | "gym" | "streetwear"; price: string; image: string; description: string; gender: "men" | "women" | "unisex"; featured: boolean }) => void; onUpdate: (product: ProductRow, input: { name: string; slug: string; category: "sneakers" | "gym" | "streetwear"; price: string; image: string; description: string; gender: "men" | "women" | "unisex"; featured: boolean }) => void; onDelete: (product: ProductRow) => void; onInventory: (product: ProductRow, variants: ProductRow["variants"], imageUrls: string[]) => void }) {
  const [mode, setMode] = useState<"create" | "edit" | null>(null); const [editing, setEditing] = useState<ProductRow | null>(null); const [inventoryProduct, setInventoryProduct] = useState<ProductRow | null>(null);
  const close = () => { setMode(null); setEditing(null); };
  return <><PageTitle kicker="CATALOG / 03" title="المنتجات." text="أضف وعدّل واحذف منتجاتك، وأدر المقاسات والألوان والمخزون وصور المعرض لكل منتج." action={<button onClick={() => { setEditing(null); setMode("create"); }} className="inline-flex h-11 items-center gap-2 bg-[var(--lux-acid)] px-4 text-xs font-black text-black"><Plus className="h-4 w-4" />منتج جديد</button>} />{mode === "create" ? <ProductForm key="create" title="إضافة منتج جديد" saving={saving} onSubmit={input => { onCreate(input); close(); }} /> : null}{mode === "edit" ? <ProductForm key={editing?.id} title={`تعديل ${editing?.name ?? "المنتج"}`} initial={editing} saving={saving} onSubmit={input => { if (editing) onUpdate(editing, input); close(); }} /> : null}{inventoryProduct ? <InventoryEditor key={inventoryProduct.id} product={inventoryProduct} saving={saving} onSave={(variants, imageUrls) => { onInventory(inventoryProduct, variants, imageUrls); setInventoryProduct(null); }} /> : null}<div className="mt-7 overflow-hidden border border-white/10"><div className="grid grid-cols-[54px_minmax(0,1fr)_auto] items-center gap-3 border-b border-white/10 bg-[#151515] px-4 py-3 text-[10px] font-black tracking-[.1em] text-white/40"><span>IMG</span><span>PRODUCT</span><span>PRICE</span></div>{products.map(product => <div key={product.id} className="grid grid-cols-[54px_minmax(0,1fr)_auto] items-center gap-3 border-b border-white/10 px-4 py-3 last:border-0"><img src={product.images[0]?.url ?? demoImage} alt="" className="h-12 w-[42px] object-cover" /><div className="min-w-0"><p className="truncate text-sm font-bold">{product.name}</p><p className="mt-1 text-[10px] font-bold text-white/40">{product.category} / مخزون {product.variants.reduce((sum, v) => sum + v.stockQuantity, 0)}</p></div><div className="text-left"><p className="text-sm font-black">{pounds(product.priceCents)} ج.م</p>{product.isFeatured ? <p className="mt-1 text-[9px] font-black text-[var(--lux-acid)]">FEATURED</p> : null}{Number.isFinite(Number(product.id)) ? <div className="mt-2 flex flex-wrap gap-x-3 gap-y-1"><button onClick={() => { setEditing(product); setMode("edit"); }} className="text-[10px] font-bold text-[var(--lux-acid)]">تعديل</button><button onClick={() => setInventoryProduct(product)} className="text-[10px] font-bold text-white/65">مخزون</button><button onClick={() => onDelete(product)} className="text-[10px] font-bold text-red-300">حذف</button></div> : null}</div></div>)}</div></>;
}

function EditorialManager({ type, rows, saving, onSave }: { type: "collection" | "campaign"; rows: (CollectionRow | CampaignRow)[]; saving: boolean; onSave: (input: Record<string, string>) => void }) {
  const campaign = type === "campaign"; const [show, setShow] = useState(false); const [title, setTitle] = useState(""); const [slug, setSlug] = useState(""); const [description, setDescription] = useState(""); const [imageUrl, setImageUrl] = useState(campaign ? "https://res.cloudinary.com/dbt9psvo/image/upload/luxora-lookbook-night_8e397827" : demoImage); const [kind, setKind] = useState(campaign ? "drop" : "streetwear");
  return <><PageTitle kicker={campaign ? "EDITORIAL / 05" : "CATALOG MAP / 04"} title={campaign ? "الحملات." : "المجموعات."} text={campaign ? "أنشئ Drop أو Lookbook أو عرضًا موسميًا. تُستخدم هذه البطاقات داخل الصفحات التحريرية للمتجر." : "قسّم الكتالوج كما يناسبك: كوتشيات، جيم، streetwear أو أي مجموعة جديدة."} action={<button onClick={() => setShow(!show)} className="inline-flex h-11 items-center gap-2 bg-[var(--lux-acid)] px-4 text-xs font-black text-black"><Plus className="h-4 w-4" />إضافة</button>} />{show ? <Panel title={campaign ? "إضافة حملة" : "إضافة مجموعة"} className="mt-6"><form onSubmit={event => { event.preventDefault(); onSave({ title, slug, description, imageUrl, kind }); }} className="grid gap-4 md:grid-cols-2"><Field label="العنوان" value={title} onChange={value => { setTitle(value); setSlug(value.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "")); }} /><Field label="Slug بالإنجليزية" value={slug} onChange={setSlug} /><label><span className="mb-2 block text-[10px] font-black tracking-[.08em] text-white/50">{campaign ? "نوع الحملة" : "الفئة"}</span><select value={kind} onChange={event => setKind(event.target.value)} className="h-11 w-full border border-white/15 bg-[#101010] px-3 text-sm text-white">{campaign ? <><option value="drop">Drop</option><option value="lookbook">Lookbook</option><option value="offer">Offer</option></> : <><option value="sneakers">كوتشيات</option><option value="gym">ملابس جيم</option><option value="streetwear">ملابس شبابية</option></>}</select></label><div><Field label="رابط الصورة" value={imageUrl} onChange={setImageUrl} /><CloudinaryImageUpload onUploaded={setImageUrl} /></div><div className="md:col-span-2"><TextArea label="الوصف" value={description} onChange={setDescription} /></div><button disabled={saving} className="h-11 bg-[var(--lux-acid)] text-xs font-black text-black disabled:opacity-60">{saving ? "جارٍ الحفظ..." : "حفظ"}</button></form></Panel> : null}<div className="mt-7 grid gap-3 sm:grid-cols-2">{rows.map(row => <article key={row.id} className="overflow-hidden border border-white/10 bg-[#151515]"><img src={row.imageUrl ?? demoImage} alt="" className="h-40 w-full object-cover opacity-70" /><div className="p-5"><p className="text-[10px] font-black tracking-[.12em] text-[var(--lux-acid)]">{"type" in row ? row.type.toUpperCase() : row.category.toUpperCase()}</p><h2 className="mt-2 text-lg font-black">{row.title}</h2><p className="mt-2 line-clamp-2 text-xs leading-6 text-white/50">{row.description}</p></div></article>)}</div></>;
}

const ORDER_STATUS_LABEL: Record<OrderStatus, string> = { new: "جديد", confirmed: "تم التأكيد", preparing: "قيد التجهيز", shipped: "تم الشحن", completed: "مكتمل", cancelled: "ملغي" };

function OrdersManager({ orders, saving, onStatus }: { orders: OrderRow[]; saving: boolean; onStatus: (id: number, status: OrderStatus) => void }) {
  return <><PageTitle kicker="COMMERCE / 06" title="الطلبات." text="تابع طلبات الدفع عند الاستلام، راجع بيانات العميل والمنتجات، وغيّر حالة الطلب من مكان واحد." />{orders.length ? <div className="mt-7 space-y-4">{orders.map(order => <article key={order.id} className="border border-white/10 bg-[#151515] p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4 border-b border-white/10 pb-4"><div><p className="text-[10px] font-black tracking-[.14em] text-[var(--lux-acid)]">{order.orderNumber}</p><h2 className="mt-2 text-lg font-black">{order.customerName}</h2><p className="mt-1 text-xs text-white/45">{new Date(order.createdAt).toLocaleString("ar-EG")} · {order.phone}</p></div><div className="flex items-center gap-3"><strong className="text-lg font-black">{pounds(order.totalCents)} ج.م</strong><select value={order.status} disabled={saving} onChange={event => onStatus(order.id, event.target.value as OrderStatus)} className="h-10 border border-white/20 bg-[#101010] px-3 text-xs font-bold text-white outline-none focus:border-[var(--lux-acid)]">{Object.entries(ORDER_STATUS_LABEL).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div></div><div className="mt-4 grid gap-4 lg:grid-cols-[1fr_260px]"><div className="space-y-2">{order.items.map((item, index) => <div key={`${order.id}-${index}`} className="flex min-w-0 items-start justify-between gap-3 border-b border-white/10 pb-2 text-xs"><span>{item.productName} <span className="text-white/45">({item.variantLabel}) × {item.quantity}</span></span><span className="font-bold">{pounds(item.unitPriceCents * item.quantity)} ج.م</span></div>)}</div><div className="space-y-2 text-xs leading-6 text-white/55"><p><strong className="text-white">العنوان:</strong> {order.address}</p>{order.notes ? <p><strong className="text-white">ملاحظات:</strong> {order.notes}</p> : null}<p><strong className="text-white">الدفع:</strong> عند الاستلام · <strong className="text-white">الحالة:</strong> {ORDER_STATUS_LABEL[order.status]}</p></div></div></article>)}</div> : <div className="mt-7 grid min-h-72 place-items-center border border-dashed border-white/20 text-center"><div><ClipboardList className="mx-auto h-8 w-8 text-[var(--lux-acid)]" /><h2 className="mt-4 font-display text-2xl font-black">مفيش طلبات لسه.</h2><p className="mt-2 text-xs leading-6 text-white/50">أي طلب دفع عند الاستلام هيوصل هنا تلقائيًا.</p></div></div>}</>;
}

function ShopifyPanel({ connected, onMarkReady, onImport, saving, importing }: { connected: string; onMarkReady: () => void; onImport: () => void; saving: boolean; importing: boolean }) { return <><PageTitle kicker="COMMERCE / 06" title="Shopify، تحت سيطرتك." text="استورد المنتجات المنشورة مرة واحدة لتصبح النصوص والصور والتصنيف والمختارات قابلة للتحرير داخل لوحة التحكم، مع الاحتفاظ بربط السلة والدفع الرسمي." /><div className="mt-8 grid gap-4 lg:grid-cols-[1.15fr_.85fr]"><Panel title="حالة التكامل"><div className="flex items-center gap-3"><span className={`h-3 w-3 rounded-full ${connected === "connected" ? "bg-emerald-400" : "bg-amber-300"}`} /><div><p className="font-black">{connected === "connected" ? "متصل" : "جاهز للاستيراد"}</p><p className="mt-1 text-xs text-white/45">الاستيراد يقرأ Shopify فقط، ويضيف المنتجات الجديدة دون استبدال أي تعديل حفظته هنا.</p></div></div><div className="mt-6 flex flex-wrap gap-3"><button onClick={onImport} disabled={importing} className="h-11 bg-[var(--lux-acid)] px-4 text-xs font-black text-black disabled:opacity-60">{importing ? "جارٍ الاستيراد..." : "استيراد منتجات Shopify"}</button><button onClick={onMarkReady} disabled={saving} className="h-11 border border-white/20 px-4 text-xs font-black text-white disabled:opacity-60">{saving ? "جارٍ الحفظ..." : "تحديث حالة الربط"}</button></div></Panel><Panel title="ما يبقى متصلًا"><div className="space-y-3 text-sm text-white/60"><StateLine label="عرض المنتج" value="لوحة LUXORA" /><StateLine label="السلة" value="Shopify" /><StateLine label="Checkout + payment" value="Shopify" /></div></Panel></div></>; }

export default function Admin() {
  const { loading, isAuthenticated, user } = useAuth(); const [active, setActive] = useState("overview"); const utils = trpc.useUtils();
  const overview = trpc.catalog.adminOverview.useQuery(undefined, { enabled: isAuthenticated });
  const ordersQuery = trpc.orders.list.useQuery(undefined, { enabled: isAuthenticated, retry: false });
  const saveSettings = trpc.catalog.saveSettings.useMutation({ onSuccess: () => { toast.success("تم حفظ الإعدادات."); utils.catalog.adminOverview.invalidate(); utils.catalog.snapshot.invalidate(); }, onError: error => toast.error(error.message) });
  const bootstrap = trpc.catalog.bootstrapDefaults.useMutation({ onSuccess: result => { toast.success(result.created ? "تمت تعبئة محتوى البداية في قاعدة البيانات." : "الكتالوج يحتوي بيانات بالفعل."); utils.catalog.adminOverview.invalidate(); utils.catalog.snapshot.invalidate(); }, onError: error => toast.error(error.message) });
  const importShopify = trpc.catalog.importShopifyCatalog.useMutation({ onSuccess: result => { toast.success(result.created ? `تم استيراد ${result.created} منتج ليتاح تعديلهم من لوحة التحكم.` : `لا توجد منتجات جديدة؛ تم الحفاظ على ${result.skipped} منتج معدل.`); utils.catalog.adminOverview.invalidate(); utils.catalog.snapshot.invalidate(); }, onError: error => toast.error(error.message) });
  const createProduct = trpc.catalog.createProduct.useMutation({ onSuccess: () => { toast.success("تمت إضافة المنتج."); utils.catalog.adminOverview.invalidate(); utils.catalog.snapshot.invalidate(); }, onError: error => toast.error(error.message) });
  const updateProduct = trpc.catalog.updateProduct.useMutation({ onSuccess: () => { toast.success("تم تعديل المنتج."); utils.catalog.adminOverview.invalidate(); utils.catalog.snapshot.invalidate(); }, onError: error => toast.error(error.message) });
  const deleteProduct = trpc.catalog.deleteProduct.useMutation({ onSuccess: () => { toast.success("تم حذف المنتج."); utils.catalog.adminOverview.invalidate(); utils.catalog.snapshot.invalidate(); }, onError: error => toast.error(error.message) });
  const saveVariants = trpc.catalog.saveVariants.useMutation({ onSuccess: () => { utils.catalog.adminOverview.invalidate(); utils.catalog.snapshot.invalidate(); }, onError: error => toast.error(error.message) });
  const saveImages = trpc.catalog.saveImages.useMutation({ onSuccess: () => { toast.success("تم حفظ المخزون والصور."); utils.catalog.adminOverview.invalidate(); utils.catalog.snapshot.invalidate(); }, onError: error => toast.error(error.message) });
  const saveCollection = trpc.catalog.saveCollection.useMutation({ onSuccess: () => { toast.success("تم حفظ المجموعة."); utils.catalog.adminOverview.invalidate(); utils.catalog.snapshot.invalidate(); }, onError: error => toast.error(error.message) });
  const saveCampaign = trpc.catalog.saveCampaign.useMutation({ onSuccess: () => { toast.success("تم حفظ الحملة."); utils.catalog.adminOverview.invalidate(); utils.catalog.snapshot.invalidate(); }, onError: error => toast.error(error.message) });
  const updateOrderStatus = trpc.orders.updateStatus.useMutation({ onSuccess: () => { toast.success("تم تحديث حالة الطلب."); utils.orders.list.invalidate(); }, onError: error => toast.error(error.message) });
  if (loading) return <main className="grid min-h-screen place-items-center bg-[#0c0c0c] text-white"><span className="h-7 w-7 animate-spin rounded-full border-2 border-white/20 border-t-[var(--lux-acid)]" /></main>;
  if (!isAuthenticated) return <LoginGate />;
  if (overview.isLoading || !overview.data) return <main className="grid min-h-screen place-items-center bg-[#0c0c0c] text-white">جاري تحميل لوحة التحكم...</main>;
  if (overview.error || user?.role !== "admin") return <main dir="rtl" className="grid min-h-screen place-items-center bg-[#0c0c0c] p-5 text-center text-white"><div><p className="text-[10px] font-black tracking-widest text-[var(--lux-acid)]">ACCESS RESTRICTED</p><h1 className="mt-3 font-display text-4xl font-black">صلاحيات المدير مطلوبة.</h1><p className="mt-3 text-sm text-white/55">سجّل دخولك بحساب مالك المشروع لتظهر لوحة التحكم.</p><Link href="/" className="mt-6 inline-flex h-11 items-center bg-[var(--lux-acid)] px-5 text-sm font-black text-black">العودة للمتجر</Link></div></main>;
  const data = overview.data as { settings: SettingForm & { shopifyConnectionStatus: string }; products: ProductRow[]; collections: CollectionRow[]; campaigns: CampaignRow[]; };
  const orders = (ordersQuery.data ?? []) as OrderRow[];
  const saveBrand = (form: SettingForm) => saveSettings.mutate(form);
  const create = (input: { name: string; slug: string; category: "sneakers" | "gym" | "streetwear"; price: string; image: string; description: string; gender: "men" | "women" | "unisex"; featured: boolean }) => { const amount = Number(input.price); if (!input.slug || !input.name || !input.description || !Number.isFinite(amount) || amount <= 0) { toast.error("أدخل اسمًا ووصفًا وSlug وسعرًا صحيحًا."); return; } createProduct.mutate({ name: input.name, slug: input.slug, category: input.category, priceCents: Math.round(amount * 100), description: input.description, imageUrl: input.image || null, gender: input.gender, isFeatured: input.featured }); };
  const update = (product: ProductRow, input: { name: string; slug: string; category: "sneakers" | "gym" | "streetwear"; price: string; image: string; description: string; gender: "men" | "women" | "unisex"; featured: boolean }) => { const amount = Number(input.price); const id = Number(product.id); if (!Number.isFinite(id) || !input.slug || !input.name || !input.description || !Number.isFinite(amount) || amount <= 0) { toast.error("بيانات المنتج غير مكتملة."); return; } updateProduct.mutate({ id, name: input.name, slug: input.slug, category: input.category, priceCents: Math.round(amount * 100), description: input.description, imageUrl: input.image || null, gender: input.gender, isFeatured: input.featured }); };
  const saveInventory = (product: ProductRow, variants: ProductRow["variants"], imageUrls: string[]) => { const id = Number(product.id); if (!Number.isFinite(id)) return; if (!imageUrls.length) { toast.error("أضف صورة واحدة على الأقل."); return; } saveVariants.mutate({ id, variants }); saveImages.mutate({ id, imageUrls, altText: product.name }); };
  const remove = (product: ProductRow) => { const id = Number(product.id); if (!Number.isFinite(id)) return; if (window.confirm(`حذف ${product.name} من الكتالوج؟`)) deleteProduct.mutate({ id }); };
  const saveEditorial = (type: "collection" | "campaign", input: Record<string, string>) => { if (!input.title || !input.slug || !input.description) { toast.error("أكمل العنوان والـ Slug والوصف."); return; } if (type === "collection") saveCollection.mutate({ title: input.title, slug: input.slug, description: input.description, imageUrl: input.imageUrl || null, category: input.kind as "sneakers" | "gym" | "streetwear" | "featured" }); else saveCampaign.mutate({ title: input.title, slug: input.slug, description: input.description, imageUrl: input.imageUrl || null, type: input.kind as "drop" | "lookbook" | "offer", ctaLabel: "اكتشف الآن" }); };
  let content: React.ReactNode = <Overview products={data.products} collections={data.collections} campaigns={data.campaigns} bootstrap={() => bootstrap.mutate()} busy={bootstrap.isPending} />;
  if (active === "brand") content = <BrandEditor settings={data.settings} saving={saveSettings.isPending} onSave={saveBrand} />;
  if (active === "products") content = <ProductManager products={data.products} saving={createProduct.isPending || updateProduct.isPending || deleteProduct.isPending || saveVariants.isPending || saveImages.isPending} onCreate={create} onUpdate={update} onDelete={remove} onInventory={saveInventory} />;
  if (active === "collections") content = <EditorialManager type="collection" rows={data.collections} saving={saveCollection.isPending} onSave={input => saveEditorial("collection", input)} />;
  if (active === "campaigns") content = <EditorialManager type="campaign" rows={data.campaigns} saving={saveCampaign.isPending} onSave={input => saveEditorial("campaign", input)} />;
  if (active === "orders") content = <OrdersManager orders={orders} saving={updateOrderStatus.isPending} onStatus={(id, status) => updateOrderStatus.mutate({ id, status })} />;
  if (active === "shopify") content = <ShopifyPanel connected={data.settings.shopifyConnectionStatus} saving={saveSettings.isPending} importing={importShopify.isPending} onImport={() => importShopify.mutate()} onMarkReady={() => saveSettings.mutate({ shopifyConnectionStatus: "ready" })} />;
  return <div style={{ "--lux-acid": data.settings.primaryColor || "#D9FF2F" } as React.CSSProperties}><AdminShell active={active} onActive={setActive}>{content}</AdminShell></div>;
}
